-- StoicMigration Up
CREATE TABLE IF NOT EXISTS `User` (
    `ID` INT AUTO_INCREMENT NOT NULL,
    `Email` NVARCHAR(256) NOT NULL UNIQUE,
    `EmailConfirmed` TINYINT NOT NULL,
    `Joined` DATETIME NOT NULL,
    `LastLogin` DATETIME NULL,
    `LastActive` DATETIME NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `LoginKey` (
    `UserID` INT NOT NULL,
    `Provider` INT NOT NULL,
    `Key` NVARCHAR(1024) NOT NULL,
    CONSTRAINT `FK_LoginKeyUser` FOREIGN KEY (`UserID`) REFERENCES `User` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (`UserID`, `Provider`)
);

CREATE TABLE IF NOT EXISTS `TodoItem` (
    `ID` INT AUTO_INCREMENT NOT NULL,
    `OwnerID` INT NOT NULL,
    `Message` NVARCHAR(256) NOT NULL,
    `Status` INT NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_OwnerID` FOREIGN KEY (`OwnerID`) REFERENCES `User` (`ID`) ON UPDATE CASCADE ON DELETE CASCADE
);

-- StoicMigration Down
DROP TABLE IF EXISTS `LoginKey`;
DROP TABLE IF EXISTS `TodoItem`;
DROP TABLE IF EXISTS `User`;