FROM golang:1.21-alpine

RUN apk update && apk upgrade -y && \
    apk add --no-cache \
        bash \
        git \
        gcc \
        libc-dev \
        libgit2-dev \
        curl \
        musl-dev

WORKDIR /app

COPY ./go.mod ./go.sum ./

RUN go mod download

COPY . .

RUN go build -o /app/app .

EXPOSE 8080

CMD ["/app/app"]